package com.example.moviesapp.util

object Category {
    const val POPULAR = "popular"
    const val POPULAR_TV = "popular"
    const val UPCOMING = "upcoming"
    const val TOP_RATED = "top_rated"
    const val NOW_PLAYING = "now_playing"
    const val HORROR = "horror"
    const val ROMANCE = "romance"
    const val DRAMA = "drama"
    const val HISTORY = "history"
    const val FAMILY = "family"
    const val COMEDY = "comedy"
    const val ANIMATED = "animated"
    const val ACTION = "action"
    const val MYSTERY = "mystery"
    const val ADVENTURE = "adventure"
    const val CRIME = "crime"
    const val TRENDING = "trending"
    const val SCI_FI = "scifi"
    const val AIRING_TODAY = "airing_today"
    const val Soap_Tv = "Soap_tv"
    const val Crime_Tv = "Crime_tv"
    const val Family_Tv = "Family_tv"
    const val Action_Tv = "Action_tv"
    const val Scifi_Tv = "Scifi_tv"
    const val Kids_Tv = "Kids_tv"
    const val Animated_Tv = "Animated_tv"
    const val Reality_Tv = "Reality_tv"
    const val Talk_Tv = "Talk_tv"
    const val News_Tv = "News_tv"
    const val Drama_Tv = "Drama_tv"
    const val Documentary_TV = "Documentary_tv"
    const val Comedy_Tv = "Comedy_tv"
    const val Western_Tv = "Western_tv"

    const val HOME_CATEGORY_MOVIE = "Movies"
    const val HOME_CATEGORY_TV = "TV"
  }